// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHfaew4hQjsc-e3lfB34AaNnXoELNMrV8',
    appId: '1:1052084737726:web:43d1d0d9c5efde8674b0ef',
    messagingSenderId: '1052084737726',
    projectId: 'somo-406211',
    authDomain: 'somo-406211.firebaseapp.com',
    databaseURL: 'https://somo-406211-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'somo-406211.appspot.com',
    measurementId: 'G-BLMFBF0E4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCknnhDpcguvwt54FJZ1HGh90XZ9MJ30oc',
    appId: '1:1052084737726:android:8832b9033842628474b0ef',
    messagingSenderId: '1052084737726',
    projectId: 'somo-406211',
    databaseURL: 'https://somo-406211-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'somo-406211.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCZKAO0xy-pR9hjTdLgETCmAiev8Xni9Y',
    appId: '1:1052084737726:ios:b55fd4d3b503ff6e74b0ef',
    messagingSenderId: '1052084737726',
    projectId: 'somo-406211',
    databaseURL: 'https://somo-406211-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'somo-406211.appspot.com',
    iosClientId: '1052084737726-n4m45fsohm57i7det0dp88qvi46sc9po.apps.googleusercontent.com',
    iosBundleId: 'com.example.agileFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCZKAO0xy-pR9hjTdLgETCmAiev8Xni9Y',
    appId: '1:1052084737726:ios:91d1ae93cd85445974b0ef',
    messagingSenderId: '1052084737726',
    projectId: 'somo-406211',
    databaseURL: 'https://somo-406211-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'somo-406211.appspot.com',
    iosClientId: '1052084737726-a9hs2jpsqfvu2gg7b4c5r0lvor8vmfve.apps.googleusercontent.com',
    iosBundleId: 'com.example.agileFrontend.RunnerTests',
  );
}
